image_width: 400
image_height: 320
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [9574.11312,    0.     ,  199.02711,
            0.     , 8336.10026,  165.17771,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [3.917013, -1.480888, -0.115884, 0.049727, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [9623.90234,    0.     ,  199.32121,    0.     ,
            0.     , 8355.63281,  163.18442,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]