image_width: 800
image_height: 600
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [4523.46068,    0.     ,  380.33737,
            0.     , 4718.56908, -545.15144,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.096734, -0.921896, -0.077639, -0.000230, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [4441.79443,    0.     ,  379.83618,    0.     ,
            0.     , 4334.50244, -517.27382,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]