dart_detector:
  ros__parameters:
    image_topic: "image_raw"
    model_path: "/home/pka/RM_PKA_2026_DartRack_AutoAim-main/src/dart_lighttrain/best.onnx"
    class_names: ["light"]

    input_width: 192
    input_height: 192

    conf_threshold: 0.25
    iou_threshold: 0.45

    use_cuda: false
    enable_debug: false

    # ===== 尽量贴近 2025 传统 detector 的约束 =====
    # 如果赛场里引导灯大致总在某个竖直区域，建议开 ROI
    # 设成 0 表示不用 ROI
    roi_y_min: 0
    roi_y_max: 0

    # 是否优先追踪上一帧已经选中的那个目标
    prefer_previous_target: true

    # 上一帧目标和当前候选中心的最大关联距离
    association_max_distance_px: 80.0