<?xml version="1.0"?>
<package format="3">
  <name>dart_solver</name>
  <version>0.0.1</version>
  <description>Solver for dart guidance based on guide-light center tracking</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>dart_interfaces</depend>

  <depend>eigen3_cmake_module</depend>
  <depend>eigen</depend>
  <depend>ceres-solver</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>